apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: tensorflow-container
      image: registry.twcc.ai/ngc/nvidia/tensorflow:18.10-py2
      command: [ "/bin/bash", "-c", "sleep 2147483647" ]
      resources:
        limits:
          nvidia.com/gpu: 1
  imagePullSecrets:
    - name: registry.twcc.ai
