apiVersion: v1
kind: Namespace
metadata:
  name: k8s-test
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: k8s-test
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: registry.twcc.ai/public/nginx:latest
      command: [ "/bin/bash", "-c", "sleep 2147483647" ]
  imagePullSecrets:
    - name: registry.twcc.ai
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  namespace: k8s-test
  labels:
    app: busybox
spec:
  containers:
    - name: busybox-container
      image: registry.twcc.ai/public/busybox:latest
      command: [ "/bin/sh", "-c", "sleep 2147483647" ]
  imagePullSecrets:
    - name: registry.twcc.ai
